# Generated by Django 5.2 on 2025-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.specification'),
        ),
    ]
