# Generated by Django 5.2 on 2025-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_options_alter_ticketcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['name'], 'verbose_name': 'Ticket Category', 'verbose_name_plural': 'Ticket Categories'},
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal messages are only visible to staff', verbose_name='Internal Message'),
        ),
    ]
